name: testingapp1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    
                     
  floating_action_bubble: ^1.1.4
  intl: ^0.17.0
  mysql_client: ^0.0.27
  device_info_plus: ^10.1.2
  auto_size_text: ^3.0.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  rename_app: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Light.ttf
